-- ============================================================
-- Upgrade Productos 2026-05-17 — Catálogo K7 + Texturas + FK
-- Base: shadowpa_almacen (MySQL en cPanel)
-- Aplicar en phpMyAdmin → SQL si NO hay SSH habilitado.
-- Si SSH SÍ está habilitado, mejor:
--   cd /home/shadowpa/repositories/shadow-almacen
--   php artisan migrate --force
--   php artisan db:seed --class=RalCatalogoSeeder --force
-- ============================================================

-- 1) Tabla texturas
CREATE TABLE IF NOT EXISTS `texturas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(40) NOT NULL,
  `orden` smallint unsigned NOT NULL DEFAULT 100,
  `activo` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `texturas_nombre_unique` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) Texturas iniciales (idempotente)
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Mate', 10, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Brillante', 20, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Texturizado', 30, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Martillado', 40, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Granulado', 50, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Cuero', 60, 1);
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`) VALUES ('Metálico', 70, 1);

-- 3) Tabla ral_catalogo
CREATE TABLE IF NOT EXISTS `ral_catalogo` (
  `codigo` varchar(16) NOT NULL,
  `nombre_oficial` varchar(120) NOT NULL,
  `hex` char(7) NOT NULL,
  `grupo` varchar(40) NOT NULL,
  `orden` smallint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4) Cargar los 213 colores K7
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1000', 'Beige verdoso', '#BEBD7F', 'Amarillo', 0) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1001', 'Beige', '#C2B078', 'Amarillo', 1) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1002', 'Beige arena', '#C6A664', 'Amarillo', 2) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1003', 'Amarillo señales', '#E5BE01', 'Amarillo', 3) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1004', 'Amarillo oro', '#CDA434', 'Amarillo', 4) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1005', 'Amarillo miel', '#A98307', 'Amarillo', 5) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1006', 'Amarillo maíz', '#E4A010', 'Amarillo', 6) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1007', 'Amarillo narciso', '#DC9D00', 'Amarillo', 7) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1011', 'Beige pardo', '#8A6642', 'Amarillo', 8) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1012', 'Amarillo limón', '#C7B446', 'Amarillo', 9) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1013', 'Blanco perla', '#EAE6CA', 'Amarillo', 10) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1014', 'Marfil', '#E1CC4F', 'Amarillo', 11) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1015', 'Marfil claro', '#E6D690', 'Amarillo', 12) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1016', 'Amarillo azufre', '#EDFF21', 'Amarillo', 13) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1017', 'Amarillo azafrán', '#F5D033', 'Amarillo', 14) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1018', 'Amarillo zinc', '#F8F32B', 'Amarillo', 15) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1019', 'Beige gris', '#9E9764', 'Amarillo', 16) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1020', 'Amarillo oliva', '#999950', 'Amarillo', 17) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1021', 'Amarillo colza', '#F3DA0B', 'Amarillo', 18) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1023', 'Amarillo tráfico', '#FAD201', 'Amarillo', 19) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1024', 'Amarillo ocre', '#AEA04B', 'Amarillo', 20) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1026', 'Amarillo brillante', '#FFFF00', 'Amarillo', 21) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1027', 'Amarillo curry', '#9D9101', 'Amarillo', 22) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1028', 'Amarillo melón', '#F4A900', 'Amarillo', 23) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1032', 'Amarillo retama', '#D6AE01', 'Amarillo', 24) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1033', 'Amarillo dalia', '#F3A505', 'Amarillo', 25) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1034', 'Amarillo pastel', '#EFA94A', 'Amarillo', 26) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1035', 'Beige perlado', '#6A5D4D', 'Amarillo', 27) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1036', 'Oro perlado', '#705335', 'Amarillo', 28) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL1037', 'Amarillo sol', '#F39F18', 'Amarillo', 29) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2000', 'Amarillo naranja', '#ED760E', 'Naranja', 30) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2001', 'Naranja rojizo', '#C93C20', 'Naranja', 31) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2002', 'Naranja sangre', '#CB2821', 'Naranja', 32) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2003', 'Naranja pastel', '#FF7514', 'Naranja', 33) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2004', 'Naranja puro', '#F44611', 'Naranja', 34) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2005', 'Naranja brillante', '#FF2301', 'Naranja', 35) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2007', 'Naranja brillante luminoso', '#FFA420', 'Naranja', 36) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2008', 'Rojo claro anaranjado', '#F75E25', 'Naranja', 37) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2009', 'Naranja tráfico', '#F54021', 'Naranja', 38) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2010', 'Naranja señales', '#D84B20', 'Naranja', 39) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2011', 'Naranja intenso', '#EC7C26', 'Naranja', 40) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2012', 'Naranja salmón', '#E55137', 'Naranja', 41) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL2013', 'Naranja perlado', '#C35831', 'Naranja', 42) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3000', 'Rojo fuego', '#AF2B1E', 'Rojo', 43) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3001', 'Rojo señales', '#A52019', 'Rojo', 44) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3002', 'Rojo carmín', '#A2231D', 'Rojo', 45) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3003', 'Rojo rubí', '#9B111E', 'Rojo', 46) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3004', 'Rojo púrpura', '#75151E', 'Rojo', 47) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3005', 'Rojo vino', '#5E2129', 'Rojo', 48) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3007', 'Rojo negruzco', '#412227', 'Rojo', 49) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3009', 'Rojo óxido', '#642424', 'Rojo', 50) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3011', 'Rojo pardo', '#781F19', 'Rojo', 51) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3012', 'Rojo beige', '#C1876B', 'Rojo', 52) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3013', 'Rojo tomate', '#A12312', 'Rojo', 53) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3014', 'Rosa antiguo', '#D36E70', 'Rojo', 54) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3015', 'Rosa claro', '#EA899A', 'Rojo', 55) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3016', 'Rojo coral', '#B32821', 'Rojo', 56) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3017', 'Rosa', '#E63244', 'Rojo', 57) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3018', 'Rojo fresa', '#D53032', 'Rojo', 58) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3020', 'Rojo tráfico', '#CC0605', 'Rojo', 59) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3022', 'Rojo salmón', '#D95030', 'Rojo', 60) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3024', 'Rojo brillante', '#F80000', 'Rojo', 61) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3026', 'Rojo brillante luminoso', '#FE0000', 'Rojo', 62) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3027', 'Rojo frambuesa', '#C51D34', 'Rojo', 63) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3028', 'Rojo puro', '#CB3234', 'Rojo', 64) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3031', 'Rojo oriente', '#B32428', 'Rojo', 65) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3032', 'Rojo rubí perla', '#721422', 'Rojo', 66) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL3033', 'Rosa perlado', '#B44C43', 'Rojo', 67) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4001', 'Lila rojizo', '#6D3F5B', 'Violeta', 68) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4002', 'Violeta rojizo', '#922B3E', 'Violeta', 69) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4003', 'Rosa erika', '#DE4C8A', 'Violeta', 70) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4004', 'Burdeos', '#641C34', 'Violeta', 71) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4005', 'Lila azulado', '#6C4675', 'Violeta', 72) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4006', 'Púrpura', '#A03472', 'Violeta', 73) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4007', 'Violeta', '#4A192C', 'Violeta', 74) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4008', 'Violeta de seguridad', '#924E7D', 'Violeta', 75) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4009', 'Violeta pastel', '#A18594', 'Violeta', 76) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4010', 'Magenta', '#CF3476', 'Violeta', 77) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4011', 'Violeta perla', '#8673A1', 'Violeta', 78) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL4012', 'Mora perlada', '#6C6874', 'Violeta', 79) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5000', 'Azul violeta', '#354D73', 'Azul', 80) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5001', 'Azul verdoso', '#1F3438', 'Azul', 81) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5002', 'Azul ultramar', '#20214F', 'Azul', 82) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5003', 'Azul zafiro', '#1D1E33', 'Azul', 83) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5004', 'Azul negruzco', '#18171C', 'Azul', 84) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5005', 'Azul señales', '#1E2460', 'Azul', 85) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5007', 'Azul brillante', '#3E5F8A', 'Azul', 86) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5008', 'Azul grisáceo', '#26252D', 'Azul', 87) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5009', 'Azul azur', '#025669', 'Azul', 88) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5010', 'Azul genciana', '#0E294B', 'Azul', 89) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5011', 'Azul acero', '#231A24', 'Azul', 90) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5012', 'Azul claro', '#3B83BD', 'Azul', 91) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5013', 'Azul cobalto', '#1E213D', 'Azul', 92) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5014', 'Azul paloma', '#606E8C', 'Azul', 93) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5015', 'Azul cielo', '#2271B3', 'Azul', 94) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5017', 'Azul tráfico', '#063971', 'Azul', 95) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5018', 'Azul turquesa', '#3F888F', 'Azul', 96) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5019', 'Azul capri', '#1B5583', 'Azul', 97) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5020', 'Azul océano', '#1D334A', 'Azul', 98) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5021', 'Azul agua marina', '#256D7B', 'Azul', 99) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5022', 'Azul nocturno', '#252850', 'Azul', 100) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5023', 'Azul lejanía', '#49678D', 'Azul', 101) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5024', 'Azul pastel', '#5D9B9B', 'Azul', 102) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5025', 'Azul gencia perla', '#2A6478', 'Azul', 103) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL5026', 'Azul noche perla', '#102C54', 'Azul', 104) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6000', 'Verde patina', '#316650', 'Verde', 105) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6001', 'Verde esmeralda', '#287233', 'Verde', 106) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6002', 'Verde hoja', '#2D572C', 'Verde', 107) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6003', 'Verde oliva', '#424632', 'Verde', 108) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6004', 'Verde azulado', '#1F3A3D', 'Verde', 109) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6005', 'Verde musgo', '#2F4538', 'Verde', 110) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6006', 'Verde oliva grisáceo', '#3E3B32', 'Verde', 111) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6007', 'Verde botella', '#343B29', 'Verde', 112) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6008', 'Verde parduzco', '#39352A', 'Verde', 113) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6009', 'Verde abeto', '#31372B', 'Verde', 114) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6010', 'Verde hierba', '#35682D', 'Verde', 115) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6011', 'Verde reseda', '#587246', 'Verde', 116) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6012', 'Verde negruzco', '#343E40', 'Verde', 117) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6013', 'Verde caña', '#6C7156', 'Verde', 118) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6014', 'Verde amarillento oliva', '#47402E', 'Verde', 119) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6015', 'Verde oliva negruzco', '#3B3C36', 'Verde', 120) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6016', 'Verde turquesa', '#1E5945', 'Verde', 121) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6017', 'Verde mayo', '#4C9141', 'Verde', 122) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6018', 'Verde amarillento', '#57A639', 'Verde', 123) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6019', 'Verde blanquecino', '#BDECB6', 'Verde', 124) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6020', 'Verde cromo', '#2E3A23', 'Verde', 125) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6021', 'Verde pálido', '#89AC76', 'Verde', 126) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6022', 'Verde parduzco oliva', '#25221B', 'Verde', 127) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6024', 'Verde tráfico', '#308446', 'Verde', 128) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6025', 'Verde helecho', '#3D642D', 'Verde', 129) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6026', 'Verde ópalo', '#015D52', 'Verde', 130) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6027', 'Verde luminoso', '#84C3BE', 'Verde', 131) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6028', 'Verde pino', '#2C5545', 'Verde', 132) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6029', 'Verde menta', '#20603D', 'Verde', 133) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6032', 'Verde señales', '#317F43', 'Verde', 134) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6033', 'Turquesa menta', '#497E76', 'Verde', 135) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6034', 'Turquesa pastel', '#7FB5B5', 'Verde', 136) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6035', 'Verde perla', '#1C542D', 'Verde', 137) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6036', 'Verde ópalo perla', '#193737', 'Verde', 138) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6037', 'Verde puro', '#008F39', 'Verde', 139) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL6038', 'Verde brillante', '#00BB2D', 'Verde', 140) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7000', 'Gris ardilla', '#78858B', 'Gris', 141) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7001', 'Gris plata', '#8A9597', 'Gris', 142) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7002', 'Gris oliva', '#7E7B52', 'Gris', 143) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7003', 'Gris musgo', '#6C7059', 'Gris', 144) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7004', 'Gris señales', '#969992', 'Gris', 145) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7005', 'Gris ratón', '#646B63', 'Gris', 146) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7006', 'Gris beige', '#6D6552', 'Gris', 147) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7008', 'Gris caqui', '#6A5F31', 'Gris', 148) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7009', 'Gris verdoso', '#4D5645', 'Gris', 149) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7010', 'Gris lona', '#4C514A', 'Gris', 150) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7011', 'Gris hierro', '#434B4D', 'Gris', 151) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7012', 'Gris basalto', '#4E5754', 'Gris', 152) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7013', 'Gris parduzco', '#464531', 'Gris', 153) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7015', 'Gris pizarra', '#434750', 'Gris', 154) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7016', 'Gris antracita', '#293133', 'Gris', 155) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7021', 'Gris negruzco', '#23282B', 'Gris', 156) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7022', 'Gris sombra', '#332F2C', 'Gris', 157) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7023', 'Gris hormigón', '#686C5E', 'Gris', 158) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7024', 'Gris grafito', '#474A51', 'Gris', 159) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7026', 'Gris granito', '#2F353B', 'Gris', 160) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7030', 'Gris piedra', '#8B8C7A', 'Gris', 161) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7031', 'Gris azulado', '#474B4E', 'Gris', 162) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7032', 'Gris guijarro', '#B8B799', 'Gris', 163) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7033', 'Gris cemento', '#7D8471', 'Gris', 164) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7034', 'Gris amarillento', '#8F8B66', 'Gris', 165) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7035', 'Gris luminoso', '#D7D7D7', 'Gris', 166) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7036', 'Gris platino', '#7F7679', 'Gris', 167) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7037', 'Gris polvo', '#7D7F7D', 'Gris', 168) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7038', 'Gris ágata', '#B5B8B1', 'Gris', 169) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7039', 'Gris cuarzo', '#6C6960', 'Gris', 170) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7040', 'Gris ventana', '#9DA1AA', 'Gris', 171) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7042', 'Gris tráfico A', '#8D948D', 'Gris', 172) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7043', 'Gris tráfico B', '#4E5452', 'Gris', 173) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7044', 'Gris seda', '#CAC4B0', 'Gris', 174) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7045', 'Telegris 1', '#909090', 'Gris', 175) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7046', 'Telegris 2', '#82898F', 'Gris', 176) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7047', 'Telegris 4', '#D0D0D0', 'Gris', 177) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL7048', 'Gris musgo perla', '#898176', 'Gris', 178) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8000', 'Pardo verdoso', '#826C34', 'Marrón', 179) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8001', 'Pardo ocre', '#955F20', 'Marrón', 180) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8002', 'Pardo señales', '#6C3B2A', 'Marrón', 181) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8003', 'Pardo arcilla', '#734222', 'Marrón', 182) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8004', 'Pardo cobre', '#8E402A', 'Marrón', 183) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8007', 'Pardo corzo', '#59351F', 'Marrón', 184) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8008', 'Pardo oliva', '#6F4F28', 'Marrón', 185) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8011', 'Pardo nuez', '#5B3A29', 'Marrón', 186) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8012', 'Pardo rojo', '#592321', 'Marrón', 187) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8014', 'Pardo sepia', '#382C1E', 'Marrón', 188) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8015', 'Castaño', '#633A34', 'Marrón', 189) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8016', 'Pardo caoba', '#4C2F27', 'Marrón', 190) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8017', 'Pardo chocolate', '#45322E', 'Marrón', 191) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8019', 'Pardo grisáceo', '#403A3A', 'Marrón', 192) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8022', 'Pardo negruzco', '#212121', 'Marrón', 193) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8023', 'Pardo anaranjado', '#A65E2E', 'Marrón', 194) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8024', 'Pardo beige', '#79553D', 'Marrón', 195) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8025', 'Pardo pálido', '#755C48', 'Marrón', 196) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8028', 'Pardo tierra', '#4E3B31', 'Marrón', 197) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL8029', 'Pardo cobre perla', '#763C28', 'Marrón', 198) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9001', 'Blanco crema', '#FDF4E3', 'Blanco/Negro', 199) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9002', 'Blanco grisáceo', '#E7EBDA', 'Blanco/Negro', 200) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9003', 'Blanco señales', '#F4F4F4', 'Blanco/Negro', 201) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9004', 'Negro señales', '#282828', 'Blanco/Negro', 202) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9005', 'Negro intenso', '#0A0A0A', 'Blanco/Negro', 203) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9006', 'Aluminio blanco', '#A5A5A5', 'Blanco/Negro', 204) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9007', 'Aluminio gris', '#8F8F8F', 'Blanco/Negro', 205) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9010', 'Blanco puro', '#FFFFFF', 'Blanco/Negro', 206) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9011', 'Negro grafito', '#1C1C1C', 'Blanco/Negro', 207) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9016', 'Blanco tráfico', '#F6F6F6', 'Blanco/Negro', 208) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9017', 'Negro tráfico', '#1E1E1E', 'Blanco/Negro', 209) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9018', 'Blanco papiro', '#D7D7D7', 'Blanco/Negro', 210) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9022', 'Gris claro perla', '#9C9C9C', 'Blanco/Negro', 211) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
INSERT INTO `ral_catalogo` (`codigo`, `nombre_oficial`, `hex`, `grupo`, `orden`) VALUES ('RAL9023', 'Gris oscuro perla', '#828282', 'Blanco/Negro', 212) ON DUPLICATE KEY UPDATE nombre_oficial=VALUES(nombre_oficial), hex=VALUES(hex), grupo=VALUES(grupo), orden=VALUES(orden);
-- Total colores insertados: 213

-- 5) Alterar productos: agregar textura_id + hex_override, poblar, dropear textura
ALTER TABLE `productos` ADD COLUMN `textura_id` bigint unsigned NULL AFTER `ral`;
ALTER TABLE `productos` ADD COLUMN `hex_override` char(7) NULL AFTER `nombre_interno`;

-- 5a) Salvaguarda: si en producción hay productos con texturas que no están
--     en la tabla todavía (ej. un valor custom que se agregó a mano), las
--     agregamos antes del UPDATE para que el JOIN matche y no se pierdan datos.
INSERT IGNORE INTO `texturas` (`nombre`, `orden`, `activo`)
SELECT DISTINCT productos.textura, 100, 1
FROM `productos`
WHERE productos.textura IS NOT NULL
  AND productos.textura NOT IN (SELECT nombre FROM texturas);

-- 5b) Poblar textura_id desde la string anterior
UPDATE `productos` p
JOIN `texturas` t ON t.nombre = p.textura
SET p.textura_id = t.id
WHERE p.textura_id IS NULL;

-- 5c) Verificación previa al DROP — si esto devuelve > 0, NO continuar:
--     habría productos cuya textura no se logró mapear y perderías datos.
-- SELECT id, ral, textura FROM productos WHERE textura_id IS NULL;

-- 5d) Sustituir constraint único y dropear columna vieja
ALTER TABLE `productos` DROP INDEX `uk_producto`;
ALTER TABLE `productos` DROP COLUMN `textura`;
ALTER TABLE `productos` ADD UNIQUE KEY `uk_producto` (`ral`, `textura_id`, `brillo_pct`);
ALTER TABLE `productos` ADD CONSTRAINT `productos_textura_id_foreign` FOREIGN KEY (`textura_id`) REFERENCES `texturas`(`id`);

-- 6) Registrar las 3 migraciones como aplicadas para que `php artisan migrate` no las vuelva a correr
INSERT IGNORE INTO `migrations` (`migration`, `batch`)
SELECT m, (SELECT COALESCE(MAX(batch),0)+1 FROM `migrations`) FROM (
  SELECT '2026_05_17_120000_create_texturas_table' AS m UNION
  SELECT '2026_05_17_120100_create_ral_catalogo_table' UNION
  SELECT '2026_05_17_120200_alter_productos_textura_to_fk'
) AS t;

-- 7) Verificación
SELECT 'texturas' AS tabla, COUNT(*) AS filas FROM texturas
UNION ALL SELECT 'ral_catalogo', COUNT(*) FROM ral_catalogo
UNION ALL SELECT 'productos con textura_id', COUNT(*) FROM productos WHERE textura_id IS NOT NULL;
-- Esperado: 7 texturas, 213 ral_catalogo, productos según producción.
